name: Cypress integration test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  cypress:
    name: Cypress integration test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: setup env
        run: |
          mkdir -p .vercel
          echo "$VERCEL_PROJECT_JSON" > .vercel/project.json
          pnpm setenv --token "$VERCEL_TOKEN"
        env:
          VERCEL_PROJECT_JSON: ${{ secrets.VERCEL_PROJECT_JSON }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - uses: cypress-io/github-action@v6
        id: cypress
        with:
          install: false
          browser: chrome
          headless: true
          build: pnpm build
          start: pnpm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 30
        env:
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APP_AWS_ACCESS_KEY_ID: ${{ secrets.APP_AWS_ACCESS_KEY_ID }}
          APP_AWS_SECRET_ACCESS_KEY: ${{ secrets.APP_AWS_SECRET_ACCESS_KEY }}
